name: Vault Sync App Runner

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      name:
        description: 'Environment to run against'
        type: string
        required: true

jobs:

  run:
    runs-on: ubuntu-latest
    environment: ${{ inputs.name }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Checkout Config
        uses: actions/checkout@v3
        with:
          repository: "bcgov-nr/vault-sync-config"
          token: ${{ secrets.GH_PAT }}
          path: config
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - name: Install jq tool
        run: |
          sudo apt-get update
          sudo apt-get install jq
      # Runs script to obtain Vault token
      - name: Run Vault Script
        run: sh ./.github/workflows/vault-token-script.sh
        env:
          BROKER_ADDR: ${{ secrets.BROKER_ADDR }}
          BROKER_JWT: ${{ secrets.BROKER_JWT }}
          PROVISION_ROLE_ID: ${{ secrets.PROVISION_ROLE_ID }}
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
      - run: ./bin/dev policy-sync
        env:
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      - run: ./bin/dev group-sync
        env:
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      - run: ./bin/dev approle-sync
        env:
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      - name: Cleanup Action
        run: sh ./.github/workflows/token-cleanup-script.sh
        env:
          BROKER_ADDR: ${{ secrets.BROKER_ADDR }}
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
