name: Vault Sync App Runner

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      name:
        description: 'Environment to run against'
        type: string
        required: true

jobs:

  run:
    runs-on: ubuntu-latest
    environment: ${{ inputs.name }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Checkout Config
        uses: actions/checkout@v4
        with:
          repository: "bcgov-nr/vault-sync-config"
          token: ${{ secrets.GH_PAT }}
          path: config
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      # Runs script to obtain Vault token
      - name: Build Intention
        run: sh ./.github/workflows/broker-intention.sh
        env:
          VAULT_OCP_ACCOUNT_ID: ${{ vars.VAULT_OCP_ACCOUNT_ID }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
          GITHUB_ENVIRONMENT: ${{ inputs.name }}
      - name: Open intention
        uses: bcgov-nr/action-broker-intention-open@v1
        with:
          broker_jwt: ${{ secrets.BROKER_JWT }}
          broker_url: ${{ vars.BROKER_ADDR }}
      - name: Start configure action
        uses: bcgov-nr/action-broker-action-start@v1
        with:
          action_token: ${{ env.ACTION_TOKEN_CONFIGURE }}
          broker_url: ${{ vars.BROKER_ADDR }}
      - name: Vault login
        uses: bcgov-nr/action-broker-vault-login@v1
        with:
          action_token: ${{ env.ACTION_TOKEN_CONFIGURE }}
          broker_url: ${{ vars.BROKER_ADDR }}
          role_id: ${{ secrets.PROVISION_ROLE_ID }}
          vault_url: ${{ vars.VAULT_ADDR }}
      - run: ./bin/dev.js policy-sync
        env:
          VAULT_ADDR: ${{ vars.VAULT_ADDR }}
          BROKER_TOKEN: ${{ secrets.BROKER_TOKEN }}
      - run: ./bin/dev.js group-sync
        env:
          VAULT_ADDR: ${{ vars.VAULT_ADDR }}
          BROKER_TOKEN: ${{ secrets.BROKER_TOKEN }}
      - run: ./bin/dev.js approle-sync
        env:
          VAULT_ADDR: ${{ vars.VAULT_ADDR }}
          BROKER_TOKEN: ${{ secrets.BROKER_TOKEN }}
      - name: Revoke Vault Token Action
        uses: bcgov-nr/action-broker-vault-revoke@v1
        with:
          vault_token: ${{ env.VAULT_TOKEN }}
          vault_url: ${{ vars.VAULT_ADDR }}
      - name: End configure action
        uses: bcgov-nr/action-broker-action-end@v1
        with:
          action_token: ${{ env.ACTION_TOKEN_CONFIGURE }}
          broker_url: ${{ vars.BROKER_ADDR }}
      - name: Close intention
        uses: bcgov-nr/action-broker-intention-close@v1
        with:
          intention_token: ${{ env.INTENTION_TOKEN }}
          broker_url: ${{ vars.BROKER_ADDR }}
