name: Vault Sync App Runner
# Run this workflow every time a new commit pushed to your repository
on:
  workflow_dispatch:
    branches: [main]

jobs:

  Dev:
    uses: bcgov-nr/vault-sync-app/blob/feat/testWorkflow/.github/workflows/vault-sync-app-body.yml
    with:
      username: Dev

  Test:
    uses: bcgov-nr/vault-sync-app/blob/feat/testWorkflow/.github/workflows/vault-sync-app-body.yml
    with:
      username: Test
