name: runner-config
on: [workflow_dispatch, workflow_call]
  inputs:
    environment:
      description: 'Environment to run against'
      type: environment
      required: true

jobs:

  run:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      # Runs script to install jq cmd
      - name: Install jq
        uses: sergeysova/jq-action@v2
        with:
          cmd: jq -n env
      # Runs script to obtain Vault token
      - name: Run Vault Script
        run: sh ./.github/workflows/vault-token-script.sh
        env:
          BROKER_ADDR: ${{ secrets.BROKER_ADDR }}
          BROKER_JWT: ${{ secrets.BROKER_JWT }}
          PROVISION_ROLE_ID: ${{ secrets.PROVISION_ROLE_ID }}
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      - name: Checkout Config
        uses: actions/checkout@v3
        with:
          repository: "bcgov-nr/vault-sync-config"
          token: ${{ secrets.GH_PAT }}
          path: config
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: ./bin/dev policy-sync
        env:
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      - run: ./bin/dev group-sync
        env:
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      - run: ./bin/dev approle-sync
        env:
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      - name: Cleanup Action
        run: sh ./.github/workflows/token-cleanup-script.sh
        env:
          BROKER_ADDR: ${{ secrets.BROKER_ADDR }}
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
