name: Vault Sync App Runner

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      name:
        description: 'Environment to run against'
        type: string
        required: true

jobs:

  run:
    runs-on: ubuntu-latest
    environment: ${{ inputs.name }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Checkout Config
        uses: actions/checkout@v3
        with:
          repository: "bcgov-nr/vault-sync-config"
          token: ${{ secrets.GH_PAT }}
          path: config
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      # Runs script to obtain Vault token
      - name: Run Vault Script
        run: sh ./.github/workflows/vault-token-script.sh
        env:
          BROKER_ADDR: ${{ vars.BROKER_ADDR }}
          BROKER_JWT: ${{ secrets.BROKER_JWT }}
          PROVISION_ROLE_ID: ${{ secrets.PROVISION_ROLE_ID }}
          VAULT_ADDR: ${{ vars.VAULT_ADDR }}
          VAULT_OCP_ACCOUNT_ID: ${{ vars.VAULT_OCP_ACCOUNT_ID }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
          GITHUB_ENVIRONMENT: ${{ inputs.name }}
      - run: ./bin/dev policy-sync
        env:
          VAULT_ADDR: ${{ vars.VAULT_ADDR }}
          BROKER_TOKEN: ${{ secrets.BROKER_TOKEN }}
      - run: ./bin/dev group-sync
        env:
          VAULT_ADDR: ${{ vars.VAULT_ADDR }}
          BROKER_TOKEN: ${{ secrets.BROKER_TOKEN }}
      - run: ./bin/dev approle-sync
        env:
          VAULT_ADDR: ${{ vars.VAULT_ADDR }}
          BROKER_TOKEN: ${{ secrets.BROKER_TOKEN }}
      - name: Cleanup Action
        run: sh ./.github/workflows/token-cleanup-script.sh
        env:
          BROKER_ADDR: ${{ vars.BROKER_ADDR }}
          VAULT_ADDR: ${{ vars.VAULT_ADDR }}
      - name: Close intention
        uses: bcgov-nr/action-broker-intention-close@main
        with:
          intention_token: ${{ env.INTENTION_TOKEN }}
          broker_url: ${{ vars.BROKER_ADDR }}
