name: Vault Sync App Runner
# Run this workflow every time a new commit pushed to your repository
on:
  workflow_dispatch:
    branches: [main]
    inputs:
      environment:
        description: 'Environment to run against'
        type: environment
        required: true
jobs:
  run:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      # Runs script to obtain Vault token
      - name: Run Vault Script
        run: sh ./vault-token-script.sh

      # Set the token value
      - name: Set the value
        run: |
          echo "INTENTION_TOKEN" >> $ENV_INTENTION_TOKEN
          echo "VAULT_TOKEN" >> $ENV_VAULT_TOKEN

      - name: Checkout Config
        uses: actions/checkout@v3
        with:
          repository: "bcgov-nr/vault-sync-config"
          token: ${{ secrets.GH_PAT }}
          path: config

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: ./bin/dev policy-sync
        env:
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
      - run: ./bin/dev group-sync
        env:
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
      - run: ./bin/dev approle-sync
        env:
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
