name: Vault Sync App Pipeline
# Run this workflow every time a new commit pushed to your repository
on:
  schedule:
  - cron: "45 * * * *"
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Test:
    uses: bcgov-nr/vault-sync-app/.github/workflows/vault-sync-app-runner.yml@main
    with:
      name: Test
    secrets: inherit
    needs: Dev

  Prod:
    uses: bcgov-nr/vault-sync-app/.github/workflows/vault-sync-app-runner.yml@main
    with:
      name: Prod
    secrets: inherit
    needs: Test
