name: Vault Sync App Pipeline
# Run this workflow every time a new commit pushed to your repository
on:
  schedule:
  - cron: "45 * * * *"
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Development:
    uses: ./.github/workflows/vault-sync-app-runner.yml
    with:
      name: Development
    secrets: inherit

  Test:
    uses: ./.github/workflows/vault-sync-app-runner.yml
    with:
      name: Test
    secrets: inherit
    needs: Development

  Production:
    uses: ./.github/workflows/vault-sync-app-runner.yml
    with:
      name: Production
    secrets: inherit
    needs: Test
