name: Vault Sync App Runner
# Run this workflow every time a new commit pushed to your repository
on:
  workflow_dispatch:

jobs:
  Dev:
    uses: bcgov-nr/vault-sync-app/.github/workflows/vault-sync-app-body.yml@feat/testWorkflow
    with:
      username: Dev

  Test:
    uses: bcgov-nr/vault-sync-app/.github/workflows/vault-sync-app-body.yml@feat/testWorkflow
    with:
      username: Test
