name: Vault Sync App Runner
# Run this workflow every time a new commit pushed to your repository
on:
  workflow_dispatch:

jobs:
  Test:
    uses: bcgov-nr/vault-sync-app/.github/workflows/vault-sync-app-body.yml@feat/testWorkflow
    with:
      name: Test
    secrets: inherit

  Dev:
    uses: bcgov-nr/vault-sync-app/.github/workflows/vault-sync-app-body.yml@feat/testWorkflow
    with:
      name: Dev
    secrets: inherit
    needs: Test

  Prod:
    uses: bcgov-nr/vault-sync-app/.github/workflows/vault-sync-app-body.yml@feat/testWorkflow
    with:
      name: Prod
    secrets: inherit
    needs: Dev
